name: Update
on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    container: debian:bookworm
    env:
      GH_TOKEN: ${{ github.token }}

    steps:
      - name: Install dependencies
        run: |
          apt-get update && apt-get install --yes --no-install-recommends python3 git gh ca-certificates
      - uses: actions/checkout@v4
      - name: Run update
        run: |
          # without re-setting the safe.directory config options all git
          # commands error out, even though this should be already be set by
          # actions/checkout.
          git config --global --add safe.directory "$GITHUB_WORKSPACE"
          git config --global user.email "cool-updating-bot@mediawiki.org"
          git config --global user.name "Cool updating bot"
          gh repo set-default wikimedia/mediawiki-docker
          git checkout -b auto-update
          ./update.py --commit --pr
